In [49]:
from google.colab import drive

In [50]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [51]:
import pandas as pd

In [52]:
data_movies = pd.read_csv('/content/drive/MyDrive/Data/Movies.csv')

In [53]:
data_ratings = pd.read_csv('/content/drive/MyDrive/Data/Ratings.csv')

In [54]:
data_users = pd.read_csv('/content/drive/MyDrive/Data/Users.csv')

In [55]:
data_movies.head()

Movie ID                               Title                        Genres  \
0         1                    Toy Story (1995)   Animation|Children's|Comedy   
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy   
2         3             Grumpier Old Men (1995)                Comedy|Romance   
3         4            Waiting to Exhale (1995)                  Comedy|Drama   
4         5  Father of the Bride Part II (1995)                        Comedy   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [56]:
data_movies.drop(data_movies.columns[[3,4]], axis=1)

Movie ID                               Title  \
0            1                    Toy Story (1995)   
1            2                      Jumanji (1995)   
2            3             Grumpier Old Men (1995)   
3            4            Waiting to Exhale (1995)   
4            5  Father of the Bride Part II (1995)   
...        ...                                 ...   
3878      3948             Meet the Parents (2000)   
3879      3949          Requiem for a Dream (2000)   
3880      3950                    Tigerland (2000)   
3881      3951             Two Family House (2000)   
3882      3952               Contender, The (2000)   

                            Genres  
0      Animation|Children's|Comedy  
1     Adventure|Children's|Fantasy  
2                   Comedy|Romance  
3                     Comedy|Drama  
4                           Comedy  
...                            ...  
3878                        Comedy  
3879                         Drama  
3880                         Drama  
3881                         Drama  
3882                Drama|Thriller  

[3883 rows x 3 columns]

In [57]:
data_ratings

userId  movieId  rating
0             1     1193       5
1             1      661       3
2             1      914       3
3             1     3408       4
4             1     2355       5
...         ...      ...     ...
1000204    6040     1091       1
1000205    6040     1094       5
1000206    6040      562       5
1000207    6040     1096       4
1000208    6040     1097       4

[1000209 rows x 3 columns]

In [58]:
data_ratings.head()

userId  movieId  rating
0       1     1193       5
1       1      661       3
2       1      914       3
3       1     3408       4
4       1     2355       5

In [59]:
data_ratings.tail()

userId  movieId  rating
1000204    6040     1091       1
1000205    6040     1094       5
1000206    6040      562       5
1000207    6040     1096       4
1000208    6040     1097       4

In [60]:
data_movies.shape

(3883, 5)

In [61]:
data_ratings.shape

(1000209, 3)

In [62]:
data_users.shape

(6040, 5)

In [63]:
data_ratings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000209 entries, 0 to 1000208
Data columns (total 3 columns):
 #   Column   Non-Null Count    Dtype
---  ------   --------------    -----
 0   userId   1000209 non-null  int64
 1   movieId  1000209 non-null  int64
 2   rating   1000209 non-null  int64
dtypes: int64(3)
memory usage: 22.9 MB


In [64]:
data_ratings= pd.DataFrame(data_ratings)
print(data_ratings)

         userId  movieId  rating
0             1     1193       5
1             1      661       3
2             1      914       3
3             1     3408       4
4             1     2355       5
...         ...      ...     ...
1000204    6040     1091       1
1000205    6040     1094       5
1000206    6040      562       5
1000207    6040     1096       4
1000208    6040     1097       4

[1000209 rows x 3 columns]


In [65]:
data_ratings_array=data_ratings_array = data_ratings.pivot(index='userId', columns='movieId', values='rating').fillna(0).values



In [66]:
print(data_ratings_array)

[[5. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [3. 0. 0. ... 0. 0. 0.]]


In [67]:
import numpy as np

In [68]:
rating_mat = data_ratings.to_numpy()

In [69]:
print(rating_mat)

[[   1 1193    5]
 [   1  661    3]
 [   1  914    3]
 ...
 [6040  562    5]
 [6040 1096    4]
 [6040 1097    4]]


In [70]:
from sklearn.model_selection import train_test_split

In [71]:
X_train, X_test = train_test_split(data_ratings, test_size = 0.30, random_state = 42)

In [72]:
X_train

userId  movieId  rating
539061    3314     2787       2
6514        48      647       3
623156    3770     1079       4
77441      524     1126       1
559047    3434     2470       3
...        ...      ...     ...
259178    1586     1077       5
365838    2129     2700       5
131932     854     3102       3
671155    4033     3479       5
121958     786     1391       4

[700146 rows x 3 columns]

In [73]:
X_test

userId  movieId  rating
895536    5412     2683       2
899739    5440      904       5
55687      368     3717       4
63727      425     1721       4
822011    4942     3697       1
...        ...      ...     ...
586763    3582      329       4
589709    3597     3175       3
548798    3389     2987       4
54344      355      762       3
707718    4240     2161       4

[300063 rows x 3 columns]

In [74]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 700146 entries, 539061 to 121958
Data columns (total 3 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   userId   700146 non-null  int64
 1   movieId  700146 non-null  int64
 2   rating   700146 non-null  int64
dtypes: int64(3)
memory usage: 21.4 MB


In [75]:
print(X_train.shape)
print(X_test.shape)

(700146, 3)
(300063, 3)


In [76]:
dummy_train = X_train.copy()
dummy_test = X_test.copy()

# The movies not rated by user is marked as 1 for prediction
dummy_train = dummy_train.pivot(index = 'userId', columns = 'movieId', values = 'rating')

# The movies not rated by user is marked as 0 for evaluation
dummy_test = dummy_test.pivot(index ='userId', columns = 'movieId', values = 'rating')

dummy_train_array=dummy_train.to_numpy()
dummy_test_array=dummy_test.to_numpy()

In [77]:
print(dummy_train_array)
dummy_train_array.shape

[[ 5. nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [ 3. nan nan ... nan nan nan]]


(6040, 3664)

In [78]:
print(dummy_test_array)
dummy_test_array.shape

[[nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]


(6040, 3531)

In [79]:
dummy_train_array.shape[1]

3664

In [80]:
user_id = int(input("Enter UserID: "))

Enter UserID: 987


In [81]:
rated_items_train = np.where((~np.isnan(dummy_train_array[user_id, :]))& (dummy_train_array[user_id, :] >= 1) & (dummy_train_array[user_id, :] <= 5))[0]
rated_items_test = np.where((~np.isnan(dummy_test_array[user_id, :]))& (dummy_test_array[user_id, :] >= 1) & (dummy_test_array[user_id, :] <= 5))[0]

print(rated_items_train)

print(rated_items_test)


similarity_values = []

[ 117  143  252  464  575  588  793 1000 1006 1013 1095 1111 1118 1141
 1142 1154 1160 1194 1202 1275 1282 1354 1512 1558 1753 1769 1943 2102
 2133 2177 2346 2511 2512 2528 2557 2561 2678 2679 2680 2726 2821 2851
 2946 3024 3025 3039 3088 3176 3237 3254 3328 3337 3343 3471]
[ 277  964 1058 1106 1129 1187 1421 1748 2105 2533 2586 2664 2735 2837
 2895 3161 3164 3184 3185]


Impliment Adjusted Cosine


In [82]:
def adjusted_cosine_similarity(ratings_matrix, u, v):
    ratings_u = ratings_matrix[:, u]
    ratings_v = ratings_matrix[:, v]

    bu = np.nanmean(ratings_u)
    print
    bv = np.nanmean(ratings_v)

    centered_ratings_u = ratings_u - bu
    centered_ratings_v = ratings_v - bv

    numerator = np.nansum(centered_ratings_u * centered_ratings_v)
    denominator = np.sqrt(np.nansum(centered_ratings_u**2)) * np.sqrt(np.nansum(centered_ratings_v**2))

    if denominator == 0.0 or np.isnan(denominator):
        similarity = 0.0
    else:
        similarity = numerator / denominator
    return similarity

In [83]:
predicted_ratings = {}
similarity_values = []
similarity_dict = {}
sorted_similarity_dict={}
pos_similarity_dict={}

Weighted Sum

In [84]:
def predict_ratings(user_id, rated_items_test):
    global predicted_ratings
    global similarity_values
    global similarity_dict
    global sorted_similarity_dict
    global pos_similarity_dict
    for item_id in rated_items_test:

        for item in rated_items_train:
            similarity = adjusted_cosine_similarity(dummy_train_array, item_id, item)
            similarity_values.append(similarity)

        similarity_dict = dict(zip(rated_items_train, similarity_values))
        sorted_similarity_dict = dict(sorted(similarity_dict.items(), key=lambda x: x[1], reverse=True))
        pos_similarity_dict = {k: v for k, v in sorted_similarity_dict.items() if v > 0}

        weighted_sum = 0.0
        similarity_sum = 0.0

        for rated_item, similarity_value in pos_similarity_dict.items():
            rating = dummy_train_array[user_id, rated_item]

            weighted_sum += similarity_value * rating
            similarity_sum += similarity_value

        if similarity_sum == 0.0 or np.isnan(similarity_sum):
            predicted_rating = 0.0
        else:
            predicted_rating = weighted_sum / similarity_sum

        predicted_ratings[item_id] = predicted_rating
    # print(similarity_dict)
    return predicted_ratings

Mean Absolute Error

In [85]:
def mean_absolute_error(predicted_ratings, actual_ratings):
    abs_diff = 0.0
    count = 0

    for i in range(len(predicted_ratings)):
        if i < len(actual_ratings):
            abs_diff += abs(actual_ratings[i] - predicted_ratings[i])
            count += 1

    if count > 0:
        mae = abs_diff / count
    else:
        mae = 0.0

    return mae

In [86]:
actual_ratings = dummy_test_array[user_id, rated_items_test]
actual_ratings_dict = dict(zip(rated_items_test,actual_ratings))

In [87]:
predicted_ratings = predict_ratings(user_id, rated_items_test)
predicted_ratings_values = list(predicted_ratings.values())
mae = mean_absolute_error(predicted_ratings_values, actual_ratings)
print("\nMean Absolute Error: ", mae)



Mean Absolute Error:  0.9680376318764686


In [88]:
print(rated_items_train)
print(rated_items_test)

print("Similarity values of userID: ",user_id)
print(similarity_dict)
print("\nPredicted rating for userID: ",user_id)
print(predicted_ratings)
print("\nActual rating: ",actual_ratings_dict)
print("\nMean Absolute Error for userID: ",user_id)
print(mae)
# print("\n",rated_items_train)
# print(rated_items_test)

[ 117  143  252  464  575  588  793 1000 1006 1013 1095 1111 1118 1141
 1142 1154 1160 1194 1202 1275 1282 1354 1512 1558 1753 1769 1943 2102
 2133 2177 2346 2511 2512 2528 2557 2561 2678 2679 2680 2726 2821 2851
 2946 3024 3025 3039 3088 3176 3237 3254 3328 3337 3343 3471]
[ 277  964 1058 1106 1129 1187 1421 1748 2105 2533 2586 2664 2735 2837
 2895 3161 3164 3184 3185]
Similarity values of userID:  987
{117: 0.03933885055483186, 143: 0.007795610660548581, 252: -0.00217757859119926, 464: 0.028764415973598672, 575: 0.0369901048949281, 588: 0.05785382632781888, 793: 0.04318455393729004, 1000: 0.03429530698745882, 1006: 0.06994161960590249, 1013: 0.04542015940857925, 1095: -0.011753858915579564, 1111: 0.04175258324114107, 1118: 0.044746749427812926, 1141: 0.015502131244198707, 1142: 0.01475658720462607, 1154: 0.0661958677020113, 1160: 0.029446200283708365, 1194: 0.059824474921290165, 1202: 0.0019237402019738588, 1275: 0.020420509743368835, 1282: 0.04986166405621569, 1354: -0.0126357399641